name: Extract and Release

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: "ROM_URL"
        default: "https://liquidtelecom.dl.sourceforge.net/project/ancientrom/spes/AncientOS-13-TexasCake-v7.4.1-spes-Steel-20231212-1135-Vanilla-Final.zip?viasf=1"
      DEVICE_NAME:
        description: "DEVICE_NAME"
        default: "spes"
      EXTRACTED_FILES:
        description: "EXTRACTED_FILES"
        default: "boot.img, dtbo.img, product.img, system.img, system_ext.img"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download file
        run: curl -LJO ${{ github.event.inputs.ROM_URL }}

      - name: Extract Payload
        run: |
          chmod u+x .github/scripts/android-ota-extractor
          .github/scripts/android-ota-extractor *.zip
          echo "ZIP_FILE=$(basename -a *.zip)" >> $GITHUB_ENV
          echo "ZIP_FILE_SHA256=$(sha256sum *.zip | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ github.event.inputs.EXTRACTED_FILES }}
          name: ${{ github.event.inputs.DEVICE_NAME }}-${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: |
            Device: ${{ github.event.inputs.DEVICE_NAME }}
            Filename: [${{ env.ZIP_FILE }}](${{ github.event.inputs.ROM_URL }})
            Extracted files: ${{ github.event.inputs.EXTRACTED_FILES }}
            SHA256: ${{ env.ZIP_FILE_SHA256 }}
